### ISSUE TITLE
Request Fitur Bot

### ISSUE THREAD

**Issue by Yuri-Neko** [FadliDarmawan/haruno-md#2]
Bang request fitur nhentai donk :v
Kaya gini pake screaper
https://github.com/FadliDarmawan/haruno
Tpi versi MD :) 
Sama sama pake plugin bot nya... Klo bisa Tambah fitur nhentai dong :)

**Comment by FadliDarmawan** [comment]
ok

**Comment by Yuri-Neko** [comment]
> ok

🗿di tunggu banh 🛐

**Comment by FadliDarmawan** [comment]
tapi yang di haruno tempat mu woek kan?
soalnya kan aalag kalau run di termux perlu DNS tambahan biar ga kena internet positif
